spring:
  cloud:
    config:
      server:
        git:
          uri: file://C:\\learn\\SpringCloud
          search-paths:
            - local-config


  application:
    name: spring-cloud-config-server
server:
  port: 8888

